apiVersion: apps/v1
kind: Deployment
metadata:
  name: addition-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addition-app
  template:
    metadata:
      labels:
        app: addition-app
    spec:
      containers:
      - name: addition-app
        image: anirudhm1601/addition-app:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: addition-service
spec:
  selector:
    app: addition-app
  ports:
    - protocol: TCP
      port: 80        # External port
      targetPort: 8080 # Internal container port
  type: ClusterIP  # Or LoadBalancer/NodePort based on your setup
