apiVersion: v1
kind: Service
metadata:
  name: addition-service
spec:
  selector:
    app: addition-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort  # This should be NodePort, not ClusterIP
